version: "3.1"

services:
  db:
    image: mysql:8.0.27
    command:
      - --default-authentication-plugin=mysql_native_password
      - --innodb-use-native-aio=0
    container_name: cuidapet_db
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=cuidapet_db
      - MYSQL_ROOT_PASSWORD=cuidapet
    volumes:
      - ./mysql_data:/var/lib/mysql
