name: cuidapet_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
environment:
    sdk: ">=2.15.0 <3.0.0"

dependencies:
    args: ^2.0.0
    dotenv: ^3.0.0
    get_it: ^7.2.0
    injectable: ^1.5.0
    jaguar_jwt: ^3.0.0
    logger: ^1.1.0
    mysql1: ^0.19.2
    shelf: ^1.1.0
    shelf_router: ^1.0.0

dev_dependencies:
    build_runner: ^2.1.7
    injectable_generator: ^1.5.2
    lints: ^1.0.0
    shelf_router_generator: ^1.0.1
